
package Bookle.Cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BookleException", targetNamespace = "http://Bookie.Bookle/")
public class BookleException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -2714281133504393718L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookleException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookleException_Exception(String message, BookleException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookleException_Exception(String message, BookleException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: Bookle.Cliente.BookleException
     */
    public BookleException getFaultInfo() {
        return faultInfo;
    }

}
