
package Bookle.Cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorService", targetNamespace = "http://Bookie.Bookle/", wsdlLocation = "http://localhost:9999/ws/bookle?wsdl")
public class ControladorService
    extends Service
{

    private final static URL CONTROLADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORSERVICE_EXCEPTION;
    private final static QName CONTROLADORSERVICE_QNAME = new QName("http://Bookie.Bookle/", "ControladorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/bookle?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORSERVICE_WSDL_LOCATION = url;
        CONTROLADORSERVICE_EXCEPTION = e;
    }

    public ControladorService() {
        super(__getWsdlLocation(), CONTROLADORSERVICE_QNAME);
    }

    public ControladorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORSERVICE_QNAME, features);
    }

    public ControladorService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORSERVICE_QNAME);
    }

    public ControladorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORSERVICE_QNAME, features);
    }

    public ControladorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookleControlador
     */
    @WebEndpoint(name = "ControladorPort")
    public BookleControlador getControladorPort() {
        return super.getPort(new QName("http://Bookie.Bookle/", "ControladorPort"), BookleControlador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookleControlador
     */
    @WebEndpoint(name = "ControladorPort")
    public BookleControlador getControladorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Bookie.Bookle/", "ControladorPort"), BookleControlador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORSERVICE_EXCEPTION!= null) {
            throw CONTROLADORSERVICE_EXCEPTION;
        }
        return CONTROLADORSERVICE_WSDL_LOCATION;
    }

}
